import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  BookMarked,
  BookOpen,
  Building2,
  CalendarDays,
  Columns2,
  Dna,
  Feather,
  FileSignature,
  FileText,
  GitBranch,
  HandHelping,
  Heart,
  Home,
  Images,
  Landmark,
  Languages,
  Layers,
  LifeBuoy,
  Link2,
  LayoutGrid,
  Map,
  ListChecks,
  Mail,
  MapPin,
  MoreHorizontal,
  Music,
  Newspaper,
  Route,
  ScrollText,
  Search,
  Sparkles,
  Type,
  User,
  Users,
  UtensilsCrossed,
  Video,
} from "lucide-react";

export const NAV_ICON_KEYS = [
  "bar-chart",
  "book-marked",
  "book-open",
  "building",
  "calendar",
  "columns-2",
  "dna",
  "feather",
  "file-signature",
  "file-text",
  "git-branch",
  "hand-helping",
  "heart",
  "home",
  "images",
  "landmark",
  "languages",
  "layers",
  "layout-grid",
  "life-buoy",
  "link",
  "map",
  "list-checks",
  "mail",
  "map-pin",
  "more-horizontal",
  "music",
  "newspaper",
  "route",
  "scroll-text",
  "search",
  "sparkles",
  "type",
  "user",
  "users",
  "utensils",
  "video",
] as const;

export type NavIconKey = (typeof NAV_ICON_KEYS)[number];

export const NAV_ICONS: Record<NavIconKey, LucideIcon> = {
  "bar-chart": BarChart3,
  "book-marked": BookMarked,
  "book-open": BookOpen,
  building: Building2,
  calendar: CalendarDays,
  "columns-2": Columns2,
  dna: Dna,
  feather: Feather,
  "file-signature": FileSignature,
  "file-text": FileText,
  "git-branch": GitBranch,
  "hand-helping": HandHelping,
  heart: Heart,
  home: Home,
  images: Images,
  landmark: Landmark,
  languages: Languages,
  layers: Layers,
  "layout-grid": LayoutGrid,
  "life-buoy": LifeBuoy,
  link: Link2,
  "list-checks": ListChecks,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  "more-horizontal": MoreHorizontal,
  music: Music,
  newspaper: Newspaper,
  route: Route,
  "scroll-text": ScrollText,
  search: Search,
  sparkles: Sparkles,
  type: Type,
  user: User,
  users: Users,
  utensils: UtensilsCrossed,
  video: Video,
};

export function resolveNavIcon(key: NavIconKey): LucideIcon {
  return NAV_ICONS[key];
}
